### ISSUE TITLE
Release 0.5.8

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_control#123]
I was planning on releasing 0.5.8 today, but since I'll be be absent in the coming weeks, I'd rather defer it until my return in case the release does not go smoothly. If there are minor enhancements pending that could land in 0.5.8, please mention them here or issue a PR.

**Comment by davetcoleman** [comment]
Gazebo 2.0.0 was released yesterday and with it, gazebo_ros_control was updated. It is currently breaking on the build farm because it has dependencies on the latest `joint_limits_interface` because of this commit https://github.com/ros-controls/ros_control/commit/746aed88a26b5fcaa0b59052ea210329b7234a69

I'm going to go ahead and release ros_control now since I need to get this downstream package building.

**Comment by davetcoleman** [comment]
https://github.com/ros/rosdistro/pull/2346
