### ISSUE TITLE
MoveIt Controller Manager Integration

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#131]
Has anyone begun or have plans to work on a better controller manager for ros_control that implements the MoveIt controller manager interface?

Currently for MoveIt integration I'm using the [moveit_simple_controller_manager](https://github.com/ros-planning/moveit_plugins/tree/hydro-devel/moveit_simple_controller_manager) but it is really redundant to run that when ros_control already has its own [controller manager](https://github.com/ros-controls/ros_control/tree/hydro-devel/controller_manager) that almost implements the same functionality. It seems we should adapt the ros_control controller manager somehow to directly connect to the [moveit controller manager interface](https://github.com/ros-planning/moveit_core/blob/hydro-devel/controller_manager/include/moveit/controller_manager/controller_manager.h).

Thoughts?
@isucan @sachinchitta

**Comment by mikeferguson** [comment]
I'm not sure it is redundant. Personally, my take on "controller manager" within MoveIt is that it is poorly named. It really is a "controller interface", in that it takes plans from MoveIt, and tweaks them into the proper messages/actions/etc such that they can be sent to the actual controllers. In reality, it is neither a controller nor a manager.

The real question I guess is: do you really want your controllers running _inside_ MoveIt? Personally, I would think the answer is "no", that the controllers should be separate from MoveIt itself, and thus the simple controller manager is the proper item (although a poor name), because it converts MoveIt's plan into a ROS action which is sent to your externally running controllers (which are safely in a separate process).

**Comment by adolfo-rt** [comment]
Since the ROS API of ros_control's controller manager is the same as that of the PR2 controller manager, you should be able to use the [pr2_moveit_controller_manager](https://github.com/ros-planning/moveit_pr2/tree/hydro-devel/pr2_moveit_plugins/pr2_moveit_controller_manager) out of the box. We have a colleague here that is integrating ros_control with MoveIt! and so far this approach has proved successful. He pretty much took [this](http://moveit.ros.org/wiki/PR2/Gazebo/Quick_Start#pr2_moveit_controller_manager.launch) launch file and modified the namespaces (to remove the 'pr2_' strings).

The [pr2_moveit_controller_manager code](https://github.com/ros-planning/moveit_pr2/tree/hydro-devel/pr2_moveit_plugins/pr2_moveit_controller_manager/src) has some PR2-specifics inside, like hardcoded gripper strings, but creating a PR2-agnostic plugin should be little work.

**Comment by adolfo-rt** [comment]
> Personally, my take on "controller manager" within MoveIt is that it is poorly named. It really is a "controller interface", in that it takes plans from MoveIt, and tweaks them into the proper messages/actions/etc such that they can be sent to the actual controllers. In reality, it is neither a controller nor a manager.

+1

**Comment by davetcoleman** [comment]
Great point @adolfo-rt, thanks!

**Comment by davetcoleman** [comment]
Closing this issue. I agree it would be nice to rename the MoveIt! component to controller interface.

**Comment by adolfo-rt** [comment]
Just for the record. I looked into this back then, and realized that some ROS message definitions are not the same between the pr2 and ros_control variants of the controller manager. This means that more than a rename is required.

**Comment by davetcoleman** [comment]
@mikeferguson's moveit_simple_controller_manager does a pretty good job of bridging the gap, though.

**Comment by adolfo-rt** [comment]
It does. The main limitation here is that it works with a static set of controllers. If the set of running  controllers in your robot changes frequently this can become an issue.

The PR2 version has a mode (which can be disabled) in which you allow it to reason about the available controllers, so it can start/stop them to have the right set running for the execution of a given motion plan. This mode takes full advantage of the `controller_manager`'s ROS API.

**Comment by 130s** [comment]
> I agree it would be nice to rename the MoveIt! component to controller interface. 

+1. That helps understanding for beginners and intermediates like me.

**Comment by azeey** [comment]
[The Moveit Wiki ](http://moveit.ros.org/wiki/Executing_Trajectories_with_MoveIt) seems to suggest that you'd use moveit_simple_controller_manager for simple use cases while for more complicated cases you'd use ros_control implying (at least to me) that moveit_simple_controller_manager would not be needed when using ros_control.

**Comment by davetcoleman** [comment]
I actually wrote that, and at the time I don't think I fully understood the various requirements. I actually currently use the moveit_simple_controller_manager with ros_control. To do otherwise requires writing a good bit of custom software, or hacking the old pr2_controller_manager, which is what many people including myself have done in the past.

**Comment by dyouakim** [comment]
Hey,

I know it is an old post, I was just wondering how to start my own controller in python, as I can not find the equivalent for  moveit_controller_manager::MoveItControllerHandle in python and I don't know how to start and which functions I have to implement

**Comment by adolfo-rt** [comment]
@dyouakim,

This issue is about better bindings between ros_control and MoveIt!. Your question is on the MoveIt! side of things. I know it can get confusing, as both ros_control and MoveIt! have the concept of a 'controller manager'. Anyway, you should consider addressing your question to the [moveit-users](http://moveit.ros.org/support/) mailing list.

**Comment by dyouakim** [comment]
Thanks a lot, I already posted the question there, hopefully I will get an idea how to start.

**Comment by mathias-luedtke** [comment]
I have implemented a moveit plugin for accessing ros_control nodes: https://github.com/ros-planning/moveit_plugins/pull/12
