### ISSUE TITLE
residual dependancy in controller_manager?

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#2]
The controller_manager manifest.xml lists pr2_controller_interface as a dependency.

I'm guessing that this is a leftover and isn't needed.

I have also opened a separate issue to ask how to manage these things in the future (e.g. using fork and pull etc.)

**Comment by wmeeusse** [comment]
I think that's not needed any more, but I'll double check. At some point we moved the pr2_controller_interface package into the new controller manager to allow it to load the old style controllers too. And since the pr2_controller_interface package has no bad dependencies, that kept the dependency tree of the new controller manager clean. But I believe that we have an alternative approach now that still allows us to load the old style controllers, but does not require us to move the pr2_controller_interface package any more.

**Comment by wmeeusse** [comment]
Fixed
