### ISSUE TITLE
Use new urdf SharedPtr typedefs

### ISSUE THREAD

**Issue by nxdefiant** [ros-controls/ros_control#250]
Urdf has moved to SharedPtr typedefs.

`boost::shared_ptr<const urdf::Joint> urdf_joint`
now becomes 
`urdf::JointConstSharedPtr urdf_joint`

in getJointLimits() and getSoftJointLimits() from joint_limits_interface/joint_limits_urdf.h.

**Comment by bmagyar** [comment]
I was wondering how this didn't come up for you before than
`ros_controllers`.

I'll refactor 'em

On 3 Sep 2016 10:17, "nxdefiant" notifications@github.com wrote:

Urdf has moved to SharedPtr typedefs.

boost::shared_ptr<const urdf::Joint> urdf_joint
now becomes
urdf::JointConstSharedPtr urdf_joint

in getJointLimits() and getSoftJointLimits() from
joint_limits_interface/joint_limits_urdf.h.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ros-controls/ros_control/issues/250, or mute the thread

**Comment by nxdefiant** [comment]
Probably because those functions are in a header. The compiler ignored all previous inclusion of the headers and only nagged when gazebo called them.

**Comment by bmagyar** [comment]
Could you please give a shot to #251 and make a :+1: there if it works? I don't want to rely only on my testing :)

**Comment by nxdefiant** [comment]
:+1:
