### ISSUE TITLE
controller_info catkin_make problem with ur_modern_driver

### ISSUE THREAD

**Issue by pkuttam** [ros-controls/ros_control#262]
controller_info.h in hardware_interface in kinetic-devel doesn't consist variable std::string hardware_interface;. It causes error in catkin_build ur_modern_driver. I think, we have to modify the /opt/ros/include/hardware_interface/controller_info.h and include the line
 std::string hardware_interface;

**Comment by bmagyar** [comment]
Hi,

the problem is likely the version you are using. Which ROS distro are we
talking about and which operating system?



On 8 Feb 2017 07:14, "pkuttam" <notifications@github.com> wrote:

controller_info.h in hardware_interface in kinetic-devel doesn't consist
variable std::string hardware_interface;. It causes error in catkin_build
ur_modern_driver. I think, we have to modify the
/opt/ros/include/hardware_interface/controller_info.h
and include the line
std::string hardware_interface;

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-controls/ros_control/issues/262>, or mute the thread

**Comment by pkuttam** [comment]
Thank you. I understand it now. UR_MODERN_DRIVER has no release for ros-distro kinetic-devel.
