### ISSUE TITLE
Lunar release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-controls/ros_control#269]
Hi `ros_control` maintainers!

As you may know the next ROS release Lunar Loggerhead is around the corner :tada: 

All dependencies of `ros_control` are now released into Lunar! Please consider making a Lunar release soon to unlock [downstream packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22ros_control%22&s=6&r=1).

Thanks!

**Comment by mathias-luedtke** [comment]
I have restarted the [lunar travis job](https://travis-ci.org/ros-controls/ros_control/jobs/213375251)
Update: test fails for now as `ros_controllers` misses dependencies. I have updated the tests in #270

**Comment by mathias-luedtke** [comment]
@mikaelarguedas: `ros-lunar-urdf` is not yet in `ros-shadow-fixed` (but in testing). How often do they get synced?

**Comment by bmagyar** [comment]
Thanks for the note!  I've started releasing bits,  all doc &  source jobs
are in already.

As Mathias said,  urdf was missing so far.


On Apr 11, 2017 09:55, "Mathias Lüdtke" <notifications@github.com> wrote:

@mikaelarguedas <https://github.com/mikaelarguedas>: ros-lunar-urdf is not
yet in ros-shadow-fixed (but in testing). How often do they get synced?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-controls/ros_control/issues/269#issuecomment-293194399>,
or mute the thread

**Comment by mikaelarguedas** [comment]
@ipa-mdl @bmagyar Indeed the Debian jobs failed yesterday, they are turning over now and should be available for all platforms in shadow-fixed very soon. Sorry about that

**Comment by mathias-luedtke** [comment]
Tests have passed :tada:

**Comment by bmagyar** [comment]
Thanks! I'll double check with a pre-release and start pulling triggers.

**Comment by mikaelarguedas** [comment]
Thanks all for the quick release! I'm going to close this then. All jobs are green :tada: (the ARM ones haven't turned over though)
