### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by kalectro** [ros-controls/ros_control#32]
Hi,

I looked through the wiki pages and a little into the code and would like to know what the status of the project is. The wiki states: "is not even completely written yet"
Is that still true? Is there any plan to publish it? I unfortunately found it a little too late but I seriously consider implementing your controllers for my robot. If this project is ready to use it would be great to have it a little more visible, maybe on ros.org

Kai

**Comment by wmeeusse** [comment]
Hey Kai,

This project is still under active development, which means it's still not feature complete and the api's might still change.  For this reason we haven't yet made a wide public announcement yet, but as you can see all the code is public already, and the core of the controller management is fully functional and already actively used.  So depending on how much stability you require for your project, this new controller infrastructure could be very useful. The last release into Groovy is already outdated, so should definitely use a source checkout if you plan to use this infrastructure.  There are a few wiki pages that explain basic usage of the framework to get you started.

Wim

**Comment by kalectro** [comment]
Hey Wim, 

thank you for the reply. Unfortunately I discovered this project a little too late and already wrote my own position and velocity controller. Is there an approximate release date? I think that even though the API is not stable there should be a wiki article on ros.org to increase visibility and to summarize which features are implemented and which are still on the ToDo list. 

Kai

**Comment by ahendrix** [comment]
+1; is there a stability/release plan for this in the near future?

This is currently a dependency for the core PR2 infrastructure, so it's important that it be stable enough to support a mature robot. In particular, I'm looking forward to a stable, catkinized release for Hydro so that I can release catkinized PR2 stacks.

**Comment by jbohren** [comment]
Well I do have a catkinized branch that I'm working on here and could be the basis for a hydro-devel branch: https://github.com/willowgarage/ros_control/pull/40

**Comment by davetcoleman** [comment]
+1 for getting this stable enough to be released in Hydro. With MoveIt! just officially released, a lot of people are looking for good controllers to use with MoveIt. There has been discussion and confusion on the MoveIt! mailing list if ros_control is the way to go. Are you guys looking for community involvement on this project?

**Comment by adolfo-rt** [comment]
Community involvement is always welcome :) and will be necessary if we want to see ros_control make it to Hydro. I know there is confusion among MoveIt! users on whether ros_control is the way to go. If we can land a good release with decent documentation, that confusion should go away.

To provide a satisfactory out-of-the-box experience for MoveIt! users, these items should be addressed:
- Implementing an equivalent of the PR2's **JointTrajectoryActionController**, which exposes the **FollowJointTrajectory** action interface.
- Complete the **catkinization** effort started by @jbohren.
- Test **Hydro integration**, add to release builds.
- Add **documentation** to the ros_control / MoveIt! wikis to take users by the hand on how to setup ros_control + MoveIt!

I'm willing to shift my priorities and start coding the **JointTrajectoryActionController** in one-two weeks if others can pick up the remaining tasks.

I'll post a message on the robot control sig to measure interest of the Hydro release. The sig has more visibility than this issue.

**Comment by davetcoleman** [comment]
That would be great adolfo, I will be working on various aspects of ros_control to work with MoveIt and Gazebo and will be documenting it. I'm happy to help where needed.

**Comment by davetcoleman** [comment]
Status update:

> - Implementing an equivalent of the PR2's JointTrajectoryActionController, which exposes the FollowJointTrajectory action interface.

What is the status of this? I'm starting to think about this now and was wondering who is working on it. I've reviewed @jbohren's [reflexxes_controllers](https://github.com/jhu-lcsr/reflexxes_controllers) and it looks pretty good. There is this [proposal on trajectory_interfaces](https://github.com/ros-controls/ros_control/issues/74) that looks promising. It seems to me we need MultiJointControllers.

> - Complete the catkinization effort started by @jbohren.

Completed.

> - Test Hydro integration, add to release builds.

Completed, would like to release an update to Hydro soon.

> - Add documentation to the ros_control / MoveIt! wikis to take users by the hand on how to setup ros_control + MoveIt!

I've added a lot of [documentation](http://ros.org/wiki/ros_control), though it needs to be reviewed by those who know more about ros_control that I.

**Comment by adolfo-rt** [comment]
> Implementing an equivalent of the PR2's JointTrajectoryActionController, which exposes the FollowJointTrajectory action interface.

This is my currently active task. I don't expect results before the end of the month. Since it's an API addition, we can always land it after the Hydro release.

I'm focusing on feature-parity with the existing PR2 controller, while trying to accommodate as best as possible what has been discussed so far on trajectory interfaces. I haven't been very present on the trajectory interface discussion because I'm still getting a grip on what I'd like from it. I'll jump back in the discussion soon with concrete proposals.

@jbohren controller is very nice, and it's serving as inspiration. Two important things that need addressing are: The action interface is missing, which brings along path and goal constraints, and a lot of code complexity; and the hardcoded choice of Reflexxes for interpolation. 

I'm developing the controller [here](https://github.com/pal-robotics/ros_controllers/tree/joint_trajectory_controller/joint_trajectory_controller). There's not much now, but the implementation should address the concerns mentioned above.

P.S. [This](https://github.com/pal-robotics/ros_controllers/blob/joint_trajectory_controller/joint_trajectory_controller/include/joint_trajectory_controller/trajectory_interface.h#L117-L124) is how the binary search for an active trajectory segment looks like. Compact and STL-ish (also cryptic like STL ;-).

**Comment by jbohren** [comment]
@adolfo-rt Great stuff! I do like the STL-based binary search, but is there a reason you implemented findSegment instead of using [`std::algorithm::binary_search`](http://www.cplusplus.com/reference/algorithm/binary_search/)? I looked into that when I was implementing my orocos-based trajectory component, but I think I just wanted it to be more self-describing. The documentation is really good, do you think you could put a note in there about how this implements a binary search as long as the trajectory is properly ordered?

Also, with respect to an action interface, @davetcoleman added it to my reflexxes controller, and should be merged in soon: https://github.com/davetcoleman/reflexxes_controllers/compare/action_server

**Comment by jbohren** [comment]
Also also, I like the continued use of this issue for discussing development specific to ros_control.

**Comment by adolfo-rt** [comment]
> @adolfo-rt Great stuff! I do like the STL-based binary search, but is there a reason you implemented findSegment instead of using std::algorithm::binary_search? 

Oddly enough `std::binary_search` only tells you if an element is found in the sequence, ie. it returns a bool, not an iterator. If you want iterators, then you have to use the lesser known `std::upper_bound`, `std::lower_bound` or `std::equal_range`.

> I looked into that when I was implementing my orocos-based trajectory component, but I think I just wanted it to be more self-describing. The documentation is really good, do you think you could put a note in there about how this implements a binary search as long as the trajectory is properly ordered?

There's [this](https://github.com/pal-robotics/ros_controllers/blob/joint_trajectory_controller/joint_trajectory_controller/include/joint_trajectory_controller/trajectory_interface.h#L112). Maybe a similar statement should be made explicit on the [sample](https://github.com/pal-robotics/ros_controllers/blob/joint_trajectory_controller/joint_trajectory_controller/include/joint_trajectory_controller/trajectory_interface.h#L85) method as well.

> Also, with respect to an action interface, @davetcoleman added it to my reflexxes controller, and should be merged in soon: https://github.com/davetcoleman/reflexxes_controllers/compare/action_server

The original controller implementation has a realtime-action-server-goal-handle, which can be found in the first part of the [header file](https://code.ros.org/svn/wg-ros-pkg/stacks/pr2_controllers/trunk/robot_mechanism_controllers/include/robot_mechanism_controllers/joint_trajectory_action_controller.h). It seems that setting the goal handle status can incur in non-realtime-friendly behavior. This of course is irrelevant for simulation, but critical for a hardware deployment. Any thoughts on this?.

An additional feature that should be added to a fully compliant action interface is trajectory and goal tolerance validation. This is tricky to get right, as path tolerances are associated to individual trajectory segments and goal handles. In the original implementation, all this information is mixed together in a single data structure: `Segment`, which makes it impossible to use multiple trajectory representations/interpolators. I hope to decouple these aspects in the coming days.

**Comment by davetcoleman** [comment]
> Also also, I like the continued use of this issue for discussing development specific to ros_control.

Now that ros_control has been officially announced at ROS Con and has been available in Hydro and Indigo, can we close this thread?
