### ISSUE TITLE
can ros_control surpport sdf format?

### ISSUE THREAD

**Issue by zapplelove** [ros-controls/ros_control#369]
In my robot, there are loops, and the urdf can't solve this, so I use the sdf format to describe the robot, and it can be spawned into gazebo. But when I use the plugin tag to use the libgazebo_ros_control.so, it tells me there is no robot tag.
So I can't control my robot by ROS

**Comment by bmagyar** [comment]
Hello,

Thank you for your interest in `ros_control`.
Indeed `ros_control` currently doesn't support loading SDF files just as well as many visualizers and kinematics libraries. We would be happy to accept pull requests from you implementing this feature. You may also need to enable using SDF instead of urdf on other ROS components depending on the `/robot_description` parameter.

Best,
Bence
