### ISSUE TITLE
Discussion on different APIs

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#5]
Since the Redwood arm has separate motor and joint encoders, it might be nice to distinguish between them and have an easy way for the controllers to use one or the other.

the JointStateInterface currently uses the function names getPosition, getVelocity. Might be good to change this to getMotorPosition, getJointPosition ... (one set could be in the JointStateInterface and the other in MotorStateInterface).

This might be worth a short discussion because we haven't really thought about what all will get affected by it.

**Comment by wmeeusse** [comment]
This is the prefect time to start thinking about all the interfaces you'd like to see on the redwood arm.  Let's use this ticket to collect all the different API's you'd like to have to your robot. Once we have a pretty complete set, we can revisit the naming of the API's and come up with a consistent scheme.

So your first requirement is the ability to have interfaces on both motors and joints.

**Comment by advaitjain** [comment]
Adding thoughts about different possible extensions to this issue (we can prune, select and consolidate later):

Can we add a parameter to the controller.yaml file that is essentially a down sampling rate? e.g. call joint state controller every 10th cycle.

Something like this would also be useful for thin wrappers around controllers written in Simulink whose only goal is to provide a ROS interface and thus can afford to run at a slower rate.

The code for reading the param from the parameter server and running at a lower rate could live inside each individual controller too (but that would potentially involve code duplication).

**Comment by wmeeusse** [comment]
So we spent some time thinking about all the possible interfaces you could want for a robot, and... the list is pretty much endless. In the current design,  the entire API of every single possible interface needs to have globally unique names. This would force us to come up with crazy long descriptive names. So, we decided to modify the design on the hardware interfaces from an inheritance scheme to a composition scheme. This will automatically scope the API of the interfaces to just the interface itself. The resulting usage turns out to be more compact and more clear, and will carry us much further into the future.  You can check out the documentation on the wiki https://github.com/willowgarage/ros_control/wiki/hardware_interface. The only thing that changed is the way you implement your robot. There are no changes on the controller side.

**Comment by vpradeep07** [comment]
"There are no changes on the controller side"....

Although, since we no longer need unique method names for each interface type, we shortened the method names from `getEffortJointHandle()` or `getPositionJointHandle()` to `getJointHandle()`.  Thus, this will require a small rename change in your controllers.

**Comment by advaitjain** [comment]
cool! I think this is a nice change to the design.

Things seem fine with the simple robot class that I'm working with right now. I'll let you all know if I have questions or feedback.
