### ISSUE TITLE
RealtimePublisher appears to be making a syscall

### ISSUE THREAD

**Issue by advaitjain** [ros-controls/ros_control#8]
calling unlockAndPublish() causes the RealtimePublisher to make a syscall. If I comment out that line from my code, I don't see any syscalls.

What other information would you guys need to track this down?

**Comment by rpwilson** [comment]
Which syscall is it? Restart the computer, start the userspace RTAI loop, and then look at dmesg for the syscall number. Restart is needed because RTAI will only kprintf the first syscall resulting in a hard-soft transition after booting the system to avoid spamming the buffer. 

Actually, you might be able to avoid a restart everytime you want to check for the syscall message by reinserting all the RTAI kernel modules...  I haven't tried this, but there's a good chance that the 'first warning flag' in RTAI will get reset (it's probably in rtai_sched.ko somewhere..)

**Comment by advaitjain** [comment]
Here it is:
[11265.172327] LXRT CHANGED MODE (SYSCALL), PID = 10930, SYSCALL = 240.

240 seems to be a futex.

Thanks a lot for the tip about reinserting all the kernel modules Rob. Rebooting was enough of a pain that I didn't want to dig into it.

**Comment by rpwilson** [comment]
Cool, I wasn't sure the RTAI module thing would work, but if it does that really simplifies debugging. 

In the case that you're running a 64-bit machine it looks like 240 could also be mq_open. Given the name of the offending function, it seems either syscall could make sense.

**Comment by advaitjain** [comment]
I'm on 32 bit.

**Comment by wmeeusse** [comment]
We fixed this in the default branch of ros_control. The problem occurred when the realtime loop acquired the lock, and before the realtime loop called unlock, a non-realtime loop started blocking on the lock. At that point, it's not realtime safe any more to call unlock from the realtime loop.
